# fly.toml app configuration file for rlv-minio-staging


app = "rlv-minio-staging"
primary_region = "gig"



[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "data"
  destination = "/data"



