services:
  minio:
    image: minio/minio:latest
    command: server --address :9000 --console-address :9001 /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 1212:1212
    command: -p 1212
    extra_hosts:
      - host.docker.internal:host-gateway

  app:
    depends_on:
      - minio
      - db
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent

    command: sleep infinity

    ports:
      - 3000:3000

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres-data:
  minio_data:
