name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging

jobs:
  test:
    name: Run Tests - STAGING
    runs-on: ubuntu-latest
    env:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
      MINIO_HOST: localhost
      MINIO_PORT: 9000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio -e "MINIO_ACCESS_KEY=admin" -e "MINIO_SECRET_KEY=admin1234" -v /tmp/data:/data -v /tmp/config:/root/.minio minio/minio server /data

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        env:
          MINIO_ACCESS_KEY: admin
          MINIO_SECRET_KEY: admin1234
        run: npm test

  deploy:
    name: Deploy to Railway - STAGING
    runs-on: ubuntu-latest
    needs: test
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_STAGING }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy MinIO
        run: railway up --service=${{ vars.RAILWAY_MINIO_SERVICE_ID_STAGING }}

      - name: Deploy NestJS
        run: railway up --service=${{ vars.RAILWAY_SERVICE_ID_STAGING }}
